<?php
    if (file_exists($_SERVER['DOCUMENT_ROOT'] . '/config/mysql/const.php')) {
        header("HTTP/1.0 403 Forbidden");
        exit();
    }
    echo '
    <!DOCTYPE html>
    <html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="../../css/main-style.css">
        <link rel="stylesheet" href="css/error-style.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="../../js/main-actions.js"></script>
        <script src="js/launch-action.js"></script>
        <title>Ассистент/Расписание | Ошибка</title>
    </head>
    <body>
        <div class="workspace">
            <span id="error"></span>
            <p>Информационная система пока не настроена. Если Вы системный администратор, то к информационной системе обращение идет в локальной сети. Ваш IP-адрес: <b>' . $_SERVER['REMOTE_ADDR'] . '</b></p>
        </div>
    </body>
    </html>
    ';

?>