<?php
    if (file_exists($_SERVER['DOCUMENT_ROOT'] . '/config/admin.php')) {
        header("HTTP/1.0 403 Forbidden");
        exit();
    }
echo '
    <p>Введите данные системного администратора:</p>
    <div class="input">
        <input type="text" id="admin_email" placeholder="Электронная почта">
        <span></span>
    </div>
    <div class="input">
        <input type="text" id="admin_firstName" placeholder="Имя">
        <span></span>
    </div>
    <div class="input">
        <input type="text" id="admin_lastName" placeholder="Фамилия">
        <span></span>
    </div>
    <div class="input">
        <input type="text" id="admin_middleName" placeholder="Отчество (при наличии)">
        <span></span>
    </div>
    <p>Введите данные учебного заведения.</p>
    <div class="input">
        <input type="text" id="school_data" placeholder="Наименование">
        <span></span>
    </div>
    <div class="input">
        <input type="text" id="school_admin" placeholder="ФИО методиста (сокращенно)">
        <span></span>
    </div>
    <input type="button" value="Завершить установку" onclick="finishInstallation();"></div>
';
?>