<?php
    echo '
        <div class="workspace">
            <ul class="header-menu not-selected">
                <li>
			        <a href="#">Расписание</a>
			        <ul class="header-menu-submenu">
				        <li>
			            	<a href="#">Группы</a>
			            </li>
			            <li>
			            	<a href="#">Преподаватели</a>
				        </li>
				        <li>
				        	<a href="#">Печать</a>
			            </li>
		            </ul>
                </li>
                <li class="right">
                    <a href="#">Создать расписание</a>
                </li>
            </ul>
            <div class="message-box not-selected"></div>
            
            <div class="non-selected img-sub">
                <div class="non-selected img"></div>
            </div>
        </div>
    ';
?>