<?php
    echo '
        <div class="modal"></div>
        <div class="workspace">';
    include($_SERVER['DOCUMENT_ROOT'] . '/queries/index/h-menu.phtml');
    echo '
            </ul>
            <div class="message-box not-selected"></div>
            
            <div class="non-selected img-sub">
                <div class="non-selected img"></div>
            </div>
        </div>
    </html>
    ';
?>