<?php
    echo '
    <!DOCTYPE html>
    <html lang="ru">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <link rel="stylesheet" href="css/main-style.css">
            <link rel="stylesheet" href="css/index-style.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
            <script src="js/fingerprint2.js"></script>
            <script src="js/main-actions.js? ' . time() . '"></script>
            <link href="/queries/air-datepicker/css/datepicker.min.css" rel="stylesheet" type="text/css">
            <script src="/queries/air-datepicker/js/datepicker.min.js"></script>
            <title>Ассистент/Расписание | Главная страница</title>
        </head>
    ';
?>